project_id = "pptfaxhkvzozwzzhigsv"

[functions.chat]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.admin-ai]
verify_jwt = false

[functions.ai-api]
verify_jwt = false
